apiVersion: v1
kind: Secret
metadata:
  name: gogi-secrets
  namespace: gogi

type: Opaque

stringData:

  POSTGRES_USER: gogi
  POSTGRES_PASSWORD: gogi
  POSTGRES_DB: gogi
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password